package io.github.alight77.news.ui.theme

import androidx.compose.ui.graphics.Color

internal val LightPrimary = Color(0xFF315B9C)
internal val LightPrimaryContainer = Color(0xFFD9E5FF)
internal val LightSecondary = Color(0xFF53627B)
internal val LightSecondaryContainer = Color(0xFFDCE3F3)
internal val LightTertiary = Color(0xFF346B73)
internal val LightTertiaryContainer = Color(0xFFBCEBF1)
internal val LightBackground = Color(0xFFF7F9FC)
internal val LightSurface = Color(0xFFFFFFFF)
internal val LightSurfaceContainer = Color(0xFFEEF2F8)
internal val LightSurfaceContainerLow = Color(0xFFF3F6FB)
internal val LightSurfaceVariant = Color(0xFFE5EAF2)
internal val LightOnSurface = Color(0xFF1A1C20)
internal val LightOnSurfaceVariant = Color(0xFF444B58)
internal val LightOutline = Color(0xFF747B88)

internal val DarkPrimary = Color(0xFFA9C7FF)
internal val DarkOnPrimary = Color(0xFF002E6A)
internal val DarkPrimaryContainer = Color(0xFF17477F)
internal val DarkSecondary = Color(0xFFB7C7E1)
internal val DarkSecondaryContainer = Color(0xFF39465C)
internal val DarkTertiary = Color(0xFFA4D4DB)
internal val DarkTertiaryContainer = Color(0xFF1E535A)
internal val DarkBackground = Color(0xFF111318)
internal val DarkSurface = Color(0xFF171A20)
internal val DarkSurfaceContainer = Color(0xFF20242B)
internal val DarkSurfaceContainerLow = Color(0xFF1A1E24)
internal val DarkSurfaceVariant = Color(0xFF414852)
internal val DarkOnSurface = Color(0xFFE4E7ED)
internal val DarkOnSurfaceVariant = Color(0xFFC4CAD5)
internal val DarkOutline = Color(0xFF8E96A4)
